version: "3.9"
services:
  mongodb:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: hofix
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
  backend:
    build: .
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/hofix
      JWT_SECRET_KEY: super-secret-change-me
      SECRET_KEY: dev-change-me
      SOCKET_MESSAGE_QUEUE: redis://redis:6379/0
    ports:
      - "5000:5000"
    command: python app.py
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: unless-stopped
volumes:
  mongodb_data:

